spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tale?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: root
    driver-class-name : com.mysql.cj.jdbc.Driver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5

  jpa:
    hibernate:
      ddl-auto: update  # 第一次create  第二次update
    show-sql: true
prop:
  upload-folder: D:\IDEAwork\tale\upload\\
server:
  port: 8086